export const OFFLINE_VERSION = 'ezops-version-02-99-36';
export const ORIGIN = 'https://stage.ezoperations.com';

// Combine what your SW precaches: CORE_ROUTES + PRECACHE_* + OFFLINE_APP_CACHE_ASSETS (from module.js)
export const OFFLINE_FILES: string[] = [
  // Core routes
  '/ezops/ezops-offline/index.html',
  '/ezops/ezops-offline/locations.html',
  '/ezops/ezops-offline/location.html',
  '/ezops/ezops-offline/navigation.html',

  '/ezops/ezops-offline/index.html',
  '/ezops/ezops-offline/locations.html',
  '/ezops/ezops-offline/plant.html',
  '/ezops/ezops-offline/location.html',
  '/ezops/ezops-offline/navigation.html',
  '/recommended-locations',
  '/optimizedPackages',
  '/ezops/ezops-offline/modals/taskModal.html',
  '/planner',
  '/reportDashboard',
  '/trucking',

  // CSS
  '/ezops/assets/css/bootstrap.min.css',
  '/ezops/assets/css/style_02-20.css',
  '/ezops/assets/css/rpo-icons.css',

  // Libs
  '/ezops/assets/libs/cuid.min.js',
  '/ezops/assets/libs/angular.min.js',
  '/ezops/assets/libs/angular-ui-bootstrap.min.js',
  '/ezops/assets/libs/angular-sanitize.min.js',
  '/ezops/assets/libs/chart.min.js',

  // Images/fonts
  '/ezops/assets/images/ezops-logo-black.png',
  '/ezops/assets/fonts/fontawesome-webfont.woff2',

  // Templates and modals (very important)
  '/ezops/ezops-offline/modals/taskModal.html',
  '/ezops/ezops-offline/partial/tasks.html',
  '/ezops/ezops-offline/partial/navigation/miniNav.html',

  // JS app files referenced by offline pages (short sample)
  '/ezops/apps/module.js',
  '/ezops/apps/offline/location/app.js',
  '/ezops/apps/offline/locations/locationsCtrl.js',

  '/ezops/apps/createModule.js',
  '/ezops/apps/module.js',
  '/ezops/apps/urlFactory.js',
  '/ezops/apps/mvpFactory.js',
  '/ezops/apps/offline/navigation/megaMenuCtrl.js',
  '/ezops/apps/offline/navigation/miniNavCtrl.js',
  '/ezops/apps/offline/locations/locationsCtrl.js',
  '/ezops/apps/offline/modal/syncModalCtrl.js',
  '/ezops/apps/offline/modal/versionModalCtrl.js',
  '/ezops/ezops-offline/modals/taskModal.html',
  '/ezops/assets/css/reliance-styles.css',
  '/ezops/assets/css/bootstrap.min.css',
  '/ezops/assets/css/isteven-multi-select.css',
  '/ezops/assets/css/font-awesome.min.css',
  '/assets/css/font-awesome.min.css',
  '/ezops/assets/css/angular-flash.css',
  '/ezops/assets/css/ngProgress.css',
  '/ezops/assets/css/modal-styles.css',
  '/ezops/assets/css/animation.css',
  '/ezops/assets/css/rpo-icons-codes.css',
  '/ezops/assets/css/rpo-icons-embedded.css',
  '/ezops/assets/css/rpo-icons.css',
  '/ezops/assets/libs/angular.min.js',
  '/ezops/assets/libs/angularPagination.js',
  '/ezops/assets/libs/angularFlash.js',
  '/ezops/assets/libs/ngProgress.min.js',
  '/ezops/assets/libs/angular-touch.min.js',
  '/ezops/assets/libs/moment.min.js',
  '/ezops/assets/libs/chart.min.js',
  '/ezops/assets/libs/angular-chart.min.js',
  '/ezops/assets/libs/angular-ui-bootstrap.min.js',
  '/ezops/assets/libs/angular-sanitize.min.js',
  '/ezops/assets/libs/textAngular-rangy.min.js',
  '/ezops/assets/libs/textAngular-sanitize.min.js',
  '/ezops/assets/libs/textAngular.min.js',
  '/ezops/assets/libs/isteven-multi-select.js',
  '/ezops/assets/libs/sortable.js',
  '/ezops/assets/libs/angular-inview.js',
  '/ezops/assets/images/white-ezops-colour.png',
  '/ezops/assets/images/white-reliance-colour.png',
  '/ezops/assets/images/layer-icon.png',
  '/ezops/assets/images/location-avatar.png',
  '/ezops/assets/images/category-avatar.png',
  '/ezops/assets/images/bolt.png',
  '/ezops/assets/images/compressor_icon_EZOPS_1.pngs',
  '/ezops/assets/images/pigreceiver.png',
  '/ezops/assets/images/pigsender.png',
  '/ezops/assets/images/well.png',
  '/ezops/assets/fonts/fontawesome-webfont.eot',
  '/ezops/assets/fonts/fontawesome-webfont.svg',
  '/ezops/assets/fonts/fontawesome-webfont.ttf',
  '/ezops/assets/fonts/fontawesome-webfont.woff',
  '/ezops/assets/fonts/fontawesome-webfont.woff2',
  '/ezops/assets/fonts/FontAwesome.otf',
  '/ezops/assets/fonts/univers.woff',
  '/ezops/assets/fonts/ref-delux.woff',
  '/ezops/assets/fonts/SourceSansPro-Regular.eot',
  '/ezops/assets/fonts/SourceSansPro-Regular.otf',
  '/ezops/assets/fonts/SourceSansPro-Regular.svg',
  '/ezops/assets/fonts/SourceSansPro-Regular.ttf',
  '/ezops/assets/fonts/SourceSansPro-Regular.woff',
  '/ezops/assets/fonts/SourceSansPro-Regular.woff2',
  '/ezops/assets/fonts/rpo-icons.eot',
  '/ezops/assets/fonts/rpo-icons.svg',
  '/ezops/assets/fonts/rpo-icons.ttf',
  '/ezops/assets/fonts/rpo-icons.woff',
  '/ezops/assets/fonts/rpo-icons.woff2',
  '/ezops/assets/css/icons-style.css',
  '/ezops/assets/css/mobile.css',
  '/ezops/assets/css/style_02-20.css',
  '/ezops/assets/fonts/icomoon.eot',
  '/ezops/assets/fonts/icomoon.svg',
  '/ezops/assets/fonts/icomoon.ttf',
  '/ezops/assets/fonts/icomoon.woff',
  '/ezops/assets/images/ezops-logo-black.png',
  '/ezops/assets/images/profile-avatar.png',
  '/ezops/assets/images/profile-avatar-red.png',
  '/ezops/assets/css/reset.css',
  '/ezops/apps/createModule.js',
  '/ezops/apps/urlFactory.js',
  '/ezops/apps/mvpFactory.js',
  '/ezops/apps/echo.js',
  '/ezops/apps/mapFactory.js',
  '/ezops/apps/utilitiesModule.js',
  '/ezops/apps/opAlarmTypesFactory.js',
  '/ezops/apps/offlineCostsFactory.js',
  '/ezops/apps/offlineDatabaseFactory.js',
  '/ezops/apps/offlineScheduleFactory.js',
  '/ezops/apps/onlineDatabaseFactory.js',
  '/ezops/apps/deletionFactory.js',
  '/ezops/apps/miscFactory.js',
  '/ezops/apps/formFactory.js',
  '/ezops/apps/pipelineFactory.js',
  '/ezops/apps/photoFactory.js',
  '/ezops/apps/setUpFactory.js',
  '/ezops/apps/taskFactory.js',
  '/ezops/apps/module.js',
  '/ezops/apps/offline/dashboard/app.js',
  '/ezops/apps/offline/location/app.js',
  '/ezops/apps/offline/locations/locationsCtrl.js',
  '/ezops/apps/offline/padFilter/app.js',
  '/ezops/apps/offline/calculations/app.js',
  '/ezops/apps/offline/catadynes/app.js',
  '/ezops/apps/offline/emergencyContacts/app.js',
  '/ezops/apps/offline/forms/formCtrl.js',
  '/ezops/apps/offline/forms/formsCtrl.js',
  '/ezops/apps/offline/inspectionPanel/inspectionPanelCtrl.js',
  '/ezops/apps/offline/modal/app.js',
  '/ezops/apps/offline/modal/actualCostModalCtrl.js',
  '/ezops/apps/offline/modal/equipmentInfoDisplayModalCtrl.js',
  '/ezops/apps/offline/modal/pigModalCtrl.js',
  '/ezops/apps/offline/modal/planScheduleModalCtrl.js',
  '/ezops/apps/offline/modal/syncModalCtrl.js',
  '/ezops/apps/offline/modal/versionModalCtrl.js',
  '/ezops/apps/offline/modal/taskModalCtrl.js',
  '/ezops/apps/offline/modal/taskCompletionModalCtrl.js',
  '/ezops/apps/offline/modal/pumpModalCtrl.js',
  '/ezops/apps/offline/modal/pumpReadingModalCtrl.js',
  '/ezops/apps/offline/modal/suggestedRateModalCtrl.js',
  '/ezops/apps/offline/modal/scheduleCompletionModalCtrl.js',
  '/ezops/apps/offline/modal/viewTaskModalCtrl.js',
  '/ezops/apps/offline/modal/catadyneModalCtrl.js',
  '/ezops/apps/offline/modal/toggleSenderStatusModalCtrl.js',
  '/ezops/apps/offline/note/app.js',
  '/ezops/apps/offline/pendingPigs/pendingPigsCtrl.js',
  '/ezops/apps/offline/piggingSchedule/pigsSchedulesCtrl.js',
  '/ezops/apps/offline/pigs/pigsCtrl.js',
  '/ezops/apps/offline/plantProduction/app.js',
  '/ezops/apps/offline/plungers/app.js',
  '/ezops/apps/offline/productionGraphs/app.js',
  '/ezops/apps/offline/scada/hourlyScadaCtrl.js',
  '/ezops/apps/offline/scada/scadaCtrl.js',
  '/ezops/apps/offline/schedules/schedulesCtrl.js',
  '/ezops/apps/offline/tanks/app.js',
  '/ezops/apps/offline/tanks/pumpsCtrl.js',
  '/ezops/apps/offline/tanks/tankReadingCtrl.js',
  '/ezops/apps/liquidTypeFactory.js',
  '/ezops/apps/offline/tasks/tasksCtrl.js',
  '/ezops/apps/offline/tickets/app.js',
  '/ezops/apps/offline/vessels/app.js',
  '/ezops/apps/offline/navigation/megaMenuCtrl.js',
  '/ezops/apps/offline/partial/miscItems/app.js',
  '/ezops/ezops-offline/location.html',
  '/ezops/ezops-offline/modal.html',
  '/ezops/ezops-offline/partial/inspections/inspectionsInfoTable.html',
  '/ezops/ezops-offline/partial/inspections/inspectionsPanel.html',
  '/ezops/ezops-offline/partial/calibrations.html',
  '/ezops/ezops-offline/partial/catadynes.html',
  '/ezops/ezops-offline/partial/dashboardTasks.html',
  '/ezops/ezops-offline/partial/emergencyContacts.html',
  '/ezops/ezops-offline/partial/form.html',
  '/ezops/ezops-offline/partial/forms.html',
  '/ezops/ezops-offline/partial/projectForms.html',
  '/ezops/ezops-offline/partial/images/offlineImages.html',
  '/ezops/ezops-offline/partial/metersInfoTable.html',
  '/ezops/ezops-offline/partial/miscItems.html',
  '/ezops/ezops-offline/partial/note.html',
  '/ezops/ezops-offline/partial/pigs/pendingPigs.html',
  '/ezops/ezops-offline/partial/pigs/piggingSchedule.html',
  '/ezops/ezops-offline/partial/pigs/pigs.html',
  '/ezops/ezops-offline/partial/plantProduction.html',
  '/ezops/ezops-offline/partial/plungers.html',
  '/ezops/ezops-offline/partial/productionGraphs.html',
  '/ezops/ezops-offline/partial/psvAndVessels.html',
  '/ezops/ezops-offline/partial/scada.html',
  '/ezops/ezops-offline/partial/hourlyScada.html',
  '/ezops/ezops-offline/partial/scheduledEvents.html',
  '/ezops/ezops-offline/partial/schedules.html',
  '/ezops/ezops-offline/partial/schedules/editPanel.html',
  '/ezops/ezops-offline/partial/schedulesInfoTable.html',
  '/ezops/ezops-offline/partial/siteInfo.html',
  '/ezops/ezops-offline/partial/tanks.html',
  '/ezops/ezops-offline/partial/pumps.html',
  '/ezops/ezops-offline/partial/tasks.html',
  '/ezops/ezops-offline/partial/tasks/logInfoSection.html',
  '/ezops/ezops-offline/partial/tickets.html',
  '/ezops/ezops-offline/partial/padFilter.html',
  '/ezops/ezops-offline/partial/navigation/plantsNavigation.html',
  '/ezops/ezops-offline/navigation.html',
  '/ezops/ezops-offline/partial/navigation/wellsNavigation.html',
  '/ezops/ezops-offline/partial/forms/formLogsInfo.html',
  '/ezops/ezops-offline/partial/forms/viewForm.html',
  '/ezops/ezops-offline/modals/actualCostModal.html',
  '/ezops/ezops-offline/modals/catadyneLogModal.html',
  '/ezops/ezops-offline/modals/equipmentInfoDisplayModal.html',
  '/ezops/ezops-offline/modals/formModal.html',
  '/ezops/ezops-offline/modals/imageModal.html',
  '/ezops/ezops-offline/modals/inspectionModal.html',
  '/ezops/ezops-offline/modals/invalidEquipmentHoursModal.html',
  '/ezops/ezops-offline/modals/lineEditModal.html',
  '/ezops/ezops-offline/modals/pigModal.html',
  '/ezops/ezops-offline/modals/planScheduleModal.html',
  '/ezops/ezops-offline/modals/scheduleCompletionModal.html',
  '/ezops/ezops-offline/modals/syncModal.html',
  '/ezops/ezops-offline/modals/taskModal.html',
  '/ezops/ezops-offline/modals/taskCompletionModal.html',
  '/ezops/ezops-offline/modals/tankReadingModal.html',
  '/ezops/ezops-offline/modals/pipelineInfoModal.html',
  '/ezops/ezops-offline/modals/pumpModal.html',
  '/ezops/ezops-offline/modals/pumpReadingModal.html',
  '/ezops/ezops-offline/modals/viewTaskModal.html',
  '/ezops/ezops-offline/modals/suggestedRateModal.html',
  '/ezops/ezops-offline/modals/safetyNoticeModal.html',
  '/ezops/assets/images/EZOPS-Favicon-768x768.svg',
  '/ezops/assets/images/compressor_icon_EZOPS_1.png',

  // Glyphicons fonts
  '/ezops/assets/fonts/glyphicons-halflings-regular.ttf',
  '/ezops/assets/fonts/glyphicons-halflings-regular.woff',
  '/ezops/assets/fonts/glyphicons-halflings-regular.woff2',

  // Additional JS controllers / modules
  '/ezops/apps/offline/locationSummaryCtrl.js',
  '/ezops/apps/offline/plant/plantCtrl.js',
  '/ezops/apps/offline/help/faqCtrl.js',
  '/ezops/apps/offline/equipment/equipmentCtrl.js',
  '/ezops/apps/offline/modal/loadingModalCtrl.js',
  '/ezops/apps/offline/modal/manageAlarmModalCtrl.js',
  '/ezops/apps/offline/modal/batchModalCtrl.js',

  '/ezops/apps/offline/psvsAndVessels/app.js',

  '/ezops/ezops-offline/partial/locationSummary.html',
  '/ezops/ezops-offline/partial/locationSummaryCategory.html',
  '/ezops/ezops-offline/partial/alarmDescription.html',
  '/ezops/ezops-offline/partial/additionalLocationInfo.html',
  '/ezops/ezops-offline/partial/dashboardTanks.html',
  '/ezops/ezops-offline/partial/faq.html',
  '/ezops/ezops-offline/partial/equipment.html',
  '/ezops/ezops-offline/partial/pumps/suggestedRates.html',
  '/ezops/ezops-offline/partial/psvs/psvForm.html',
  '/ezops/apps/offline/siteInfo/siteInfoCtrl.js',
  '/ezops/assets/css/icons-style.css',
  '/ezops/assets/libs/moment.min.js',
  '/ezops/apps/usersFactory.js',
  '/ezops/apps/offline/modal/deferralModalCtrl.js',
  '/ezops/apps/offline/modal/wellStatusModalCtrl.js',
  '/ezops/apps/offline/calibrations/calibrationsCtrl.js',
  // Navigation partials
  '/ezops/ezops-offline/partial/navigation/onlineMenu.html',
  '/ezops/ezops-offline/partial/navigation/configMenu.html',
  '/ezops/ezops-offline/partial/navigation/miniNav.html',

  // Extra modal templates
  '/ezops/ezops-offline/modals/loadingModal.html',
  '/ezops/ezops-offline/modals/manageAlarmModal.html',
  '/ezops/ezops-offline/modals/batchModal.html',
  '/ezops/ezops-offline/modals/pipelineInfoModal.html',
  '/ezops/ezops-offline/modals/catadyneInfoModal.html',
  '/ezops/ezops-offline/modals/catadyneModal.html',
  '/ezops/ezops-offline/modals/scheduleFormModal.html',
  '/ezops/ezops-offline/modals/switchFlowModal.html',
  '/ezops/apps/offline/modal/commentModalCtrl.js',
  '/ezops/ezops-offline/modals/commentModal.html',
  '/ezops/ezops-offline/partial/tankReadings.html',
  '/ezops/assets/images/category-avatar.png',

  '/ezops/apps/socketsFactory.js',
  '/ezops/apps/vaporUploader.js',
  '/ezops/apps/autoSyncFactory.js',
  '/ezops/apps/pigAutoSyncFactory.js',
  '/ezops/apps/onlineFormLogFactory.js',
  '/ezops/apps/analyticsFactory.js',
  '/ezops/apps/conversionFactory.js',
  '/ezops/apps/offline/modal/pipelineInfoModalCtrl.js',
  '/ezops/apps/offline/comments/commentsCtrl.js',

  '/ezops/ezops-offline/partial/pigs/pipelineInfo.html',
  '/ezops/ezops-offline/partial/pigs/pigForm.html',
  '/ezops/ezops-offline/partial/pigs/batchForm.html',
  '/ezops/ezops-offline/partial/pigs/receivingPigForm.html',
  '/ezops/ezops-offline/partial/forms/formQuestions.html',

  '/ezops/ezops-offline/modals/wellStatusModal.html',
  '/ezops/ezops-offline/modals/miscStatusChangeModal.html',
  '/ezops/ezops-offline/modals/deferralModal.html',
  '/ezops/ezops-offline/partial/tasks/tasksTable.html',


  '/ezops/ezops-offline/partial/comments/comments.html',
  '/ezops/ezops-offline/partial/acknowledgements/acknowledgements.html',
  '/ezops/ezops-offline/partial/navigation/mobileNav.html',

  // Manifest / favicon set (if not already cached elsewhere)
  '/ezops/assets/images/android-icon-36x36.png',
  '/ezops/assets/images/android-icon-48x48.png',
  '/ezops/assets/images/android-icon-72x72.png',
  '/ezops/assets/images/android-icon-96x96.png',
  '/ezops/assets/images/android-icon-144x144.png',
  '/ezops/assets/images/android-icon-192x192.png',
  '/ezops/assets/images/favicon-32x32.png',
  '/ezops/assets/images/favicon-96x96.png',
  '/ezops/assets/images/favicon-16x16.png',

  '/ezops/apps/analytics.js',
  '/ezops/assets/images/square-ezops.svg',

  '/favicon.ico',
  '/manifest.json'
  // Add the rest of OFFLINE_APP_CACHE_ASSETS from module.js here
];